apiVersion: v1
kind: Namespace
metadata:
  name: devex-eng-e-023
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-e-023
  namespace: devex-eng-e-023
  labels:
    app: eng-e-023
    requirement: eng-e-023
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eng-e-023
  template:
    metadata:
      labels:
        app: eng-e-023
    spec:
      containers:
        - name: eng-e-023
          image: eng-e-023:local
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eng-e-023
  namespace: devex-eng-e-023
spec:
  selector:
    app: eng-e-023
  ports:
    - port: 80
      targetPort: 8080
