/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


import okhttp3.*
import okhttp3.logging.HttpLoggingInterceptor
import java.io.IOException
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.suspendCancellableCoroutine
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

fun buildHttpClient(): OkHttpClient {
    val connectionPool = ConnectionPool(
        maxIdleConnections = 10,       // keep up to 10 idle connections alive
        keepAliveDuration = 5,
        timeUnit = TimeUnit.MINUTES
    )

    val loggingInterceptor = HttpLoggingInterceptor().apply {
        level = HttpLoggingInterceptor.Level.BODY   // NONE | BASIC | HEADERS | BODY
    }

    return OkHttpClient.Builder()
        // ── Timeouts ──────────────────────────────────────────────
        .connectTimeout(10, TimeUnit.SECONDS)   // TCP handshake
        .readTimeout(30, TimeUnit.SECONDS)       // waiting for server bytes
        .writeTimeout(15, TimeUnit.SECONDS)      // sending request body
        .callTimeout(60, TimeUnit.SECONDS)       // overall end-to-end cap

        // ── Connection pool ───────────────────────────────────────
        .connectionPool(connectionPool)

        // ── Interceptors (applied in order) ──────────────────────
        .addInterceptor(AuthInterceptor(apiKey = "my-secret-key"))   // application interceptor
        .addInterceptor(RetryInterceptor(maxRetries = 3))
        .addInterceptor(loggingInterceptor)                          // log last, after auth headers added
        // .addNetworkInterceptor(...)   // network interceptors fire after redirects/cache

        // ── Misc ──────────────────────────────────────────────────
        .followRedirects(true)
        .retryOnConnectionFailure(false)   // we handle retries ourselves
        .build()
}

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val client = buildHttpClient()      // one instance, shared everywhere

    // Sync call
    val body = fetchSync("https://jsonplaceholder.typicode.com/todos/1")
    println("Sync result: $body")

    // Async call
    fetchAsync("https://jsonplaceholder.typicode.com/todos/2") { result ->
        println("Async result: $result")
    }

    // POST
    val created = postJson(
        url = "https://jsonplaceholder.typicode.com/posts",
        jsonBody = """{"title":"foo","body":"bar","userId":1}"""
    )
    println("POST result: $created")

    Thread.sleep(3000)  // wait for async to complete in this toy example
    client.dispatcher.executorService.shutdown()
    client.connectionPool.evictAll()
}

// ── Helper to build a simple GET ──────────────────────────────────────────
fun getRequest(url: String): Request =
    Request.Builder()
        .url(url)
        .header("Accept", "application/json")
        .get()
        .build()
fun postJson(url: String, jsonBody: String): String? {
    val body = jsonBody.toRequestBody("application/json; charset=utf-8".toMediaType())

    val request = Request.Builder()
        .url(url)
        .post(body)
        .build()

    return client.newCall(request).execute().use { response ->
        if (!response.isSuccessful) throw IOException("HTTP ${response.code}")
        response.body?.string()
    }
}
val client = buildHttpClient()

// ─────────────────────────────────────────────────────────────────────────
// SYNCHRONOUS — blocks the calling thread; use on a background dispatcher
// ─────────────────────────────────────────────────────────────────────────
fun fetchSync(url: String): String? {
    val request = getRequest(url)

    // client.newCall(request).execute() returns Response
    // .use {} calls response.close() automatically — closes body too
    return try {
        client.newCall(request).execute().use { response ->
            if (!response.isSuccessful) {
                System.err.println("HTTP ${response.code}: ${response.message}")
                return null
            }
            // response.body is nullable; call .string() only once (streams the bytes)
            response.body?.string()
        }
    } catch (e: IOException) {
        System.err.println("Network failure: ${e.message}")
        null
    }
}

// ─────────────────────────────────────────────────────────────────────────
// ASYNCHRONOUS — OkHttp dispatches on its own thread pool; callback fires
// on that thread, NOT the main thread
// ─────────────────────────────────────────────────────────────────────────
fun fetchAsync(url: String, onResult: (String?) -> Unit) {
    val request = getRequest(url)

    client.newCall(request).enqueue(object : Callback {
        override fun onFailure(call: Call, e: IOException) {
            System.err.println("Async failure: ${e.message}")
            onResult(null)
        }

        override fun onResponse(call: Call, response: Response) {
            // Must still close the body — use .use {} inside onResponse
            response.use {
                if (!it.isSuccessful) {
                    System.err.println("HTTP ${it.code}")
                    onResult(null)
                    return
                }
                onResult(it.body?.string())
            }
        }
    })
}


// ─────────────────────────────────────────────────────────────────────────
// ASYNC with Kotlin Coroutines (recommended over raw Callback)
// ─────────────────────────────────────────────────────────────────────────

suspend fun OkHttpClient.fetchSuspend(request: Request): String {
    return suspendCancellableCoroutine { cont ->
        val call = newCall(request)

        cont.invokeOnCancellation { call.cancel() }  // respect coroutine cancellation

        call.enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) =
                cont.resumeWithException(e)

            override fun onResponse(call: Call, response: Response) {
                response.use { r ->
                    if (!r.isSuccessful) {
                        cont.resumeWithException(IOException("HTTP ${r.code}"))
                        return
                    }
                    cont.resume(r.body?.string() ?: "")
                }
            }
        })
    }
}

// Usage in a coroutine:
// val json = client.fetchSuspend(getRequest("https://api.example.com/data"))