apiVersion: v1
kind: Namespace
metadata:
  name: devex-eng-i-001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-i-001
  namespace: devex-eng-i-001
  labels:
    app: eng-i-001
    requirement: eng-i-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eng-i-001
  template:
    metadata:
      labels:
        app: eng-i-001
    spec:
      containers:
        - name: eng-i-001
          image: eng-i-001:local
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eng-i-001
  namespace: devex-eng-i-001
spec:
  selector:
    app: eng-i-001
  ports:
    - port: 80
      targetPort: 8080
