global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'portfolio-apps'
    static_configs:
      - targets: ['localhost:8000']  # FastAPI app
    metrics_path: '/metrics'
    scrape_interval: 5s