/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.utilities

import org.example.list.LinkedList

class StringUtils {
    companion object {
        fun join(source: LinkedList): String = JoinUtils.join(source)

        fun split(source: String): LinkedList = SplitUtils.split(source)
    }
}
