name: README Drift Check
on: [pull_request]

jobs:
  README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyyaml
      - run: python scripts/gen_readme_table.py --check